### ISSUE TITLE
Mid-Project Review Comments

### ISSUE THREAD

**Issue by dentness** [bobbilisantosh321/CapstoneProject-HotelManagement-System#5]
In all, I think you're well on your way to a finished product.

Just a few comments:

1. Is there any way to reduce repetition?  I see the same methods containing generic code in each of the folders.  Seems like some of this would be better suited in a common location.

2. I don't see any tests stored here.  Are there plans to add those at some time?  Automated tests are a very valuable tool when you have walked away from the project for a bit.  

3. Since you only have 4 tasks created in your project, and 3 are complete, this project should almost be complete.  Do you have all of your identified use cases covered in the code?  I was looking for admin features but didn't see those in the existing folders.  Am I just not seeing the features or have these been removed from the MVP?

4. I was looking for the part of the project holding the configuration, such as database names and any special connection details.  Is that something omitted due to security concerns or some other condition?

5. I don't know much about Django, but I don't see any database scripts for DDL.  I'm assuming the framework does its magic behind the scenes creating the database.

**Comment by bobbilisantosh321** [comment]
Thanks for the feedback:

1. Resolved few redundancies and repetitions in the code
2. Writing the tests, will push them shortly
3. All the features are accessed only by Admin. User is the admin for this application.
4. Configuration and other DB connection details are pushed
5. Django DB scripts are pushed to the repo
